version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mfr
hooks:
  BeforeInstall:
    - location: scripts/nodestop.sh      
      runas: root
  AfterInstall:
    - location: scripts/nodestart.sh      
      runas: root